package learningSpark

case class FireCallInstanceWithTimestampsWithoutRename(CallNumber: Option[Int],
                                                       UnitID: Option[String],
                                                       IncidentNumber: Option[Int],
                                                       CallType: Option[String],
                                                       IncidentDate: Option[java.sql.Timestamp],
                                                       OnWatchDate: Option[java.sql.Timestamp],
                                                       CallFinalDisposition: Option[String],
                                                       AvailableDtTS: Option[java.sql.Timestamp],
                                                       Address: Option[String],
                                                       City: Option[String],
                                                       Zipcode: Option[Int],
                                                       Battalion: Option[String],
                                                       StationArea: Option[String],
                                                       Box: Option[String],
                                                       OriginalPriority: Option[String],
                                                       Priority: Option[String],
                                                       FinalPriority: Option[Int],
                                                       ALSUnit: Option[Boolean],
                                                       CallTypeGroup: Option[String],
                                                       NumAlarms: Option[Int],
                                                       UnitType: Option[String],
                                                       UnitSequenceInCallDispatch: Option[Int],
                                                       FirePreventionDistrict: Option[String],
                                                       SupervisorDistrict: Option[String],
                                                       Neighborhood: Option[String],
                                                       Location: Option[String],
                                                       RowID: Option[String],
                                                       Delay: Option[Double]
                                                      )