services:
  mlflow:
    build: .
    container_name: mlflowContainer
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000
    networks:
      - mlflow-network

networks:
  mlflow-network:
    driver: bridge
