services:
  prometheus:
    image: prom/prometheus
    container_name: prometheusContainer
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
     - monitoring_network

  grafana:
    image: grafana/grafana
    container_name: grafanaContainer
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring_network

networks:
  monitoring_network:
    driver: bridge
