{
 "title": "Spark Basic Dashboard Standalone",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Master", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Workers Alive",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_master_aliveWorkers_Number",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Running Applications",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "metrics_master_apps_Value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Waiting Applications",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_master_waitingApps_Value",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Worker Free Cores",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_worker_coresFree_Number",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Used Cores",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "metrics_worker_coresUsed_Value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Worker Memory Usage Percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (metrics_worker_memFree_MB_Value / (metrics_worker_memFree_MB_Value + metrics_worker_memUsed_MB_Value))) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}