services:
  cassandra:
    image: cassandra:3.11
    container_name: cassandra
    ports:
      - "9042:9042"
    networks:
      - cassandra_network

networks:
  cassandra_network:
    driver: bridge